services:
  golang:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    tty: true
    volumes:
      - ./project:/go
      - pkg_store:/go/pkg
      - bin_store:/go/bin
  kube:
    image: kube:latest
    build:
      context: .
      dockerfile: ./docker/kube/Dockerfile
      target: stage1
    working_dir: /skaffold
    tty: true
    entrypoint: bash
    volumes:
      - ../k8s:/k8s
      - ../skaffold:/skaffold
      - .kube:/root/.kube
volumes:
  pkg_store:
  bin_store:
